FROM alpine

COPY trello-dashboard_linux-amd64 /app/trello-dashboard
COPY tmpl/board.html /app/tmpl/
WORKDIR /app

RUN adduser -u 2224 -s /sbin/nologin -D -H trello

USER trello

ENTRYPOINT ["/app/trello-dashboard"]

CMD []